#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <mc2023.h>
//#include <lat2eps.h>
#include <monte_carlo.h>
#include <fhelper.h>
#include <stdbool.h>
#include <ploting.h>


void teste(void);
void post(void);
void pre(void);
void mallocLattice(void);
void setupInitialConfiguration(void);
int bloqueado(int);
void interacoes(void);
unsigned int generateFile(void);
void hoshen_kopelman(int*, int*, int*);
void verificarLiberdadeVizinhos(int, int);
bool percolates2d(int, int*);
void comecar(void);
void iniciar_coleta(void);
void verificarCruzamentoInterface(void);
void updateOldValues(void);
int getInterfacialSizeOfCluster(int*);
void unique_cluster(void);
void clusterNumber(int*, int*);
//int getInterfacialLengthWith(int*, int, int);
void saveConfig(double);
void temporalEvolution(void);
void latticeEvolution(void);
void reinforcementEvolution(void);
void writeInstructions(void);

/*******************************************************************/
/**                             CONSTANTES                        **/
/*******************************************************************/

#define TEMPO_MAX               1e5		//Limits the time for measures
										//Can act like a switch for measures
#define DELTAETA_INICIAL        1./100
#define LSIZE                   64
#define NSIZE                   LSIZE * LSIZE


#define EVOLUCAO                2           // 0: NORMAL
                                            // 1: ATINGIR CONSENSO
                                            // 2: Interface Length
                                            // 3: Temporal Interface Length

#define CONFIGURACAO_I          2           // 1 : CIRCULAR
                                            // 2 : LINEAR**
                                            // 3 : ALEATORIO
/********** Measure parameters = 0(normal) *******************/
#define ESCALA                  1           // 0: LINEAR
                                            // 1: LOG
#define MEDIDAS                 6

/********** Par�metros para EVOLUCAO = 1(consensus) ****************/
#define DELTAETA_FINAL          1.0

/******* Par�metros para CONFIGURACAO_I = CIRCULAR *****************/
#define RAIO                    10          //NAO IMPLEMENTADO AINDA
/******* Par�metros para CONDICAO DE CONTORNO LINEAR FIXA **********/
#define FIXED_BORDERS			1			//non-periodic borders don't interact
#define B						1			//"b" = "boundry condition"  
											//0 -> periodic
											//1 -> dobrushin vertical(periodic horizontally)
											//2 -> dobrushin horizontal(periodic vertically)
											//3 -> square		   
#define L_INICIAL               8
#define L_FINAL                 256
/*******************************************************************/
#ifndef SAVE_CONFIG
#define SAVE_CONFIG	0
#endif

#ifndef FORCE_SEED
#define FORCE_SEED	0
#endif
#define CONFIG_T0               0	
#define CONFIG_DELTA_T          100000
#define CONFIG_TF               111000//CONFIG_T0 + 10 * CONFIG_DELTA_T



int *cima, *baixo, *esq, *dir, **vizinhos, *zelotes, *polaridade/*0, 1 */,
    *moveis, *quaisMoveis, mag, ncl, zar, interfCol;
int nMoveis0, mag0, *polaridade0, *zelotes0,  *moveis0, *quaisMoveis0,
    l0_int, l1_int, lar_int, L = LSIZE, N = NSIZE;
float *confianca, *confianca0;
int nMoveis, configSet = 0;
double tempo,deltaEta;
unsigned int seed;
FILE *fp1;

int main(void){
	printf("%.2f", pow(256 / 8.0, 1 / (float) (6-1)));	
	if(SAVE_CONFIG == 1) {
		startLatticeGif(L);
		char **l;
		l = smalloc(4 * sizeof(char*));
		l[0] = "0xEDC001";
		l[1] = "0xFFE135";
		l[2] = "0x4B0082"; 
		l[3] = "0x663399";
		setColorPallete(l, 4);
	}
    iniciar_coleta();
    if(SAVE_CONFIG == 1) printf("unset output");
    
}

void iniciar_coleta(void){
    seed = 0;
    comecar();
    return;
}


void comecar(){
	seed = generateFile();
	setupRandom(seed);
    pre();
    teste();
    writeInstructions();
    if(EVOLUCAO == 0) {
        temporalEvolution();
    } else if(EVOLUCAO == 1){
        reinforcementEvolution();
    } else if(EVOLUCAO == 2){
        latticeEvolution();
    } else if(EVOLUCAO == 3){
    	temporalEvolution();
    }
    post();
    fclose(fp1);
}

void teste(void){

}
void writeInstructions(){
	fprintf(fp1, "# Persistent Voter Model: pvm.c\n");
	fprintf(fp1, "# Data generated by: L. Possamai\n");
	fprintf(fp1, "# Seed: %d\n", seed);
	if(ESCALA == 0){
		fprintf(fp1, "# Linear Measures: %d\n", MEDIDAS);
	} else {
		fprintf(fp1, "# Log Measures: %d\n", MEDIDAS);
	}
	
	switch(EVOLUCAO){	
		case 0:
			fprintf(fp1, "# dEta = %.5f\n", DELTAETA_INICIAL);
			fprintf(fp1, "# L = %d\n", LSIZE);
			fprintf(fp1, "#  t  m  z1  z  ncl z_ar per mob int_cross\n");
			break;
		case 1:
			fprintf(fp1, "# L = %d\n", LSIZE);
			fprintf(fp1, "# Tmax = %d\n", (int)TEMPO_MAX);
			fprintf(fp1, "#  dEta  t\n");
			break;
		case 2:
			fprintf(fp1, "# dEta = %.5f\n", DELTAETA_INICIAL);
			fprintf(fp1, "# Tau_e = %d\n", (int)TEMPO_MAX);
			fprintf(fp1, "#  L int_z int_ar\n");
			break;
		case 3:
			fprintf(fp1, "# dEta = %.5f\n", DELTAETA_INICIAL);
			fprintf(fp1, "# L = %d\n", LSIZE);
			fprintf(fp1, "# Tau_e = %d\n", (int)TEMPO_MAX);
			fprintf(fp1, "#  t int_z int_ar\n");
			break;
	}
}


void post(void){
    free(dir);
    free(esq);
    free(cima);
    free(baixo);
    free(vizinhos);
    free(zelotes);
    free(confianca);
    free(polaridade);
    free(moveis);
    free(quaisMoveis);
    free(zelotes0);
    free(confianca0);
    free(polaridade0);
    free(moveis0);
    free(quaisMoveis0);

}



void pre(){
	mallocLattice();
	createNeighboursMatrix(vizinhos, N);
    setupInitialConfiguration();
    updateOldValues();
    return;
}
void mallocLattice(void){
    zelotes = smalloc(N * sizeof(int));
    zelotes0 = smalloc(N * sizeof(int));
    confianca = smalloc(N * sizeof(float));
    confianca0 = smalloc(N * sizeof(float));
    polaridade = smalloc(N * sizeof(int));
    polaridade0 = smalloc(N * sizeof(int));
    moveis = smalloc(N * sizeof(int));
    moveis0 = smalloc(N * sizeof(int));
    quaisMoveis = smalloc(N * sizeof(int));
    quaisMoveis0 = smalloc(N * sizeof(int));
    vizinhos = smalloc(N * sizeof(int*));

}

void updateOldValues(void){
    nMoveis0 = nMoveis;
    mag0 = mag;
    for(int i = 0; i < N; i++){
    	zelotes0[i] = zelotes[i];
		confianca0[i] = confianca[i];
		polaridade0[i] = polaridade[i];
		moveis0[i] = moveis[i];
		quaisMoveis0[i] = quaisMoveis[i];
    }
    
    return;
}

void saveConfig(double t){
	int *sz;
	sz = smalloc(N * sizeof(int));
	for(int i = 0; i < N; i++){
		sz[i] = 2 * polaridade0[i] + zelotes0[i];
	}
	char tLab[10] = "";
	sprintf(tLab, "%.2f", t);
	printLabelAt("t", tLab, 0.5, 0.95);
	printMatrix(sz, L);
	fflush(stdout);
}
void takeMeasures(float time){
	if(EVOLUCAO == 0){
		int z = 0;
        int z1 = 0;
        int per;
        for(int i = 0; i < N; i++){
        	if(polaridade0[i] == 1){
        		z1 += zelotes0[i];
            }
            z += zelotes0[i];
        }
        clusterNumber(&ncl,&per);
        verificarCruzamentoInterface();
        fprintf(fp1,"%.5f  %d %d %d %d %d %d %d %d\n", time, mag0, z1, z, ncl, zar, per, nMoveis0, interfCol);
	}
	if(EVOLUCAO == 2){
		unique_cluster();
		fprintf(fp1, "%d %.2f %.2f\n", L, 0.5F * (l0_int + l1_int), (float)lar_int);
	}
	if(EVOLUCAO == 3){
		unique_cluster();
		fprintf(fp1, "%.2f %.2f %.2f\n", time, 0.5F * (l0_int + l1_int), (float)lar_int);
	}
}

void temporalEvolution(void){
	float *time_arr = smalloc(MEDIDAS * sizeof(float));
	if(ESCALA == 1){
		geomProgression(time_arr, 1.0, (float)TEMPO_MAX, MEDIDAS);
	} else {
		linearProgression(time_arr, 1.0, (float)TEMPO_MAX, MEDIDAS);
	}
	
	double time = 0.0, nextTime = 0.0;
    setupInitialConfiguration();
    updateOldValues();
    deltaEta = DELTAETA_INICIAL; 
    for(int i = 0; i < MEDIDAS; i++){
    	nextTime = time_arr[i];
    	while(time < nextTime && nMoveis != 0){
    	    if(time + 1./nMoveis >= nextTime){
         		updateOldValues();
        	}
    		time += 1. / nMoveis;
    		interacoes();
    	}
    	takeMeasures(nextTime);
    	if(SAVE_CONFIG == 1) saveConfig(nextTime);
    }
    free(time_arr);
}

void latticeEvolution(){
	float *l_arr = smalloc(MEDIDAS * sizeof(float));
	if(ESCALA == 1){
		geomProgression(l_arr, L_INICIAL, L_FINAL, MEDIDAS);
	} else {
		linearProgression(l_arr, L_INICIAL, L_FINAL, MEDIDAS);
	}
	double threshold = 1.5e3;
    deltaEta = DELTAETA_INICIAL;

	for(int i = 0; i < MEDIDAS; i++){
    	L = (int) l_arr[i];
    	
    	N = L * L;
    	
      	post();
      	pre();
      	tempo = 0.0;
      	while(tempo < TEMPO_MAX){
      		tempo += 1./nMoveis;
        	interacoes();
        	if(tempo >= threshold){
				takeMeasures(threshold);
				break;
        	}
        	if(tempo + 1./nMoveis >= threshold){
          		updateOldValues();
        	}
        	if(tempo > TEMPO_MAX){
        		break;
        	}
    	}
    }
    free(l_arr);
}
void reinforcementEvolution(){
	float *dEtaArr;
	dEtaArr = smalloc(MEDIDAS * sizeof(float));
	if(ESCALA == 1){
		geomProgression(dEtaArr, DELTAETA_INICIAL, DELTAETA_FINAL, MEDIDAS);
	} else {
		linearProgression(dEtaArr, DELTAETA_INICIAL, DELTAETA_FINAL, MEDIDAS);
	}
    for(int i = 0; i < MEDIDAS; i++){
    	tempo = 0.0;
    	deltaEta = (double) dEtaArr[i];
    	while(tempo < TEMPO_MAX){
    	    tempo += 1./nMoveis;
            interacoes();
            if((mag == 0) || (mag == N)){
                fprintf(fp1,"%.7f %.6f\n",deltaEta,tempo);
                fflush(fp1);
                break;
            }
    	}
    }
    free(dEtaArr);
}


void interacoes(void){
    int pPos,pIndice, vIndice, vPos, virouZ = 0, virouN = 0, pZelote, vZelote, pIgual;

    pIndice = randomInt(nMoveis);
    pPos = moveis[pIndice];
    vIndice = randomInt(4);
    vPos = vizinhos[pPos][vIndice];

	if(!isValidInteraction(pPos, vPos, N, B)) return;
	if(FIXED_BORDERS == 1 && isOnNonPeriodicBorder(pPos, N, B)) return;
    pZelote = zelotes[pPos] == 1;
    vZelote = zelotes[vPos] == 1;
    pIgual = polaridade[pPos] == polaridade[vPos];

    if(pZelote){
        if(!pIgual){
            zelotes[pPos] = 0;
            confianca[pPos] = 0.;
            virouN = 1;
        }
    } else {
        if(!pIgual){
            polaridade[pPos] = polaridade[vPos];
            confianca[pPos] = 0.;
            if(polaridade[pPos] == 0){
                mag--;
            } else {
                mag++;
            }
        } else {
            confianca[pPos] += deltaEta;
            if(confianca[pPos] >= 1.){
                zelotes[pPos] = 1;
                virouZ = 1;
            }
        }
    }

    // locking neighbour conviction variation
    //confianca[vPos] += deltaEta;
    if((confianca[vPos] >= 1.) && !vZelote){
        zelotes[vPos] = 1;
        if(bloqueado(vPos)){
            --nMoveis;
            update_matrix(vPos, moveis[nMoveis], quaisMoveis, moveis);
        }
        verificarLiberdadeVizinhos(vPos, 0);
    }

    if(virouZ == 1){
        if(bloqueado(pPos) && quaisMoveis[pPos] < nMoveis){
            --nMoveis;
            update_matrix(pPos, moveis[nMoveis], quaisMoveis, moveis);
        }
        verificarLiberdadeVizinhos(pPos, 0);
    }

    if(virouN == 1){
        if(quaisMoveis[pPos] >= nMoveis){
            update_matrix(pPos, moveis[nMoveis], quaisMoveis, moveis);
            ++nMoveis;
        }
        verificarLiberdadeVizinhos(pPos, 1);
    }
    return;
}

void verificarLiberdadeVizinhos(int i, int verificarLivre){
    int j, k;
    for(j = 0; j < 4; j++){
        k = vizinhos[i][j];
        if(verificarLivre == 0){
            if(bloqueado(k) && (quaisMoveis[k] < nMoveis)){
                nMoveis--;
                update_matrix(k, moveis[nMoveis], quaisMoveis, moveis);
            }
        } else {
            if(quaisMoveis[k] >= nMoveis) {
                update_matrix(k, moveis[nMoveis], quaisMoveis, moveis);
                nMoveis++;
            }
        }

    }
    return;
}



void setupInitialConfiguration(void){
    int i, j = 0;
    ncl = 0;
    mag = 0;

    switch(CONFIGURACAO_I){
        case 1:break;
        case 2:
            for(i = 0; i < N; i++){
                zelotes[i] = 1;
                confianca[i] = 2.;
                if(i < N / 2){
                    polaridade[i] = 1;
                    mag++;
                } else {
                    polaridade[i] = 0;
                }
            }
            break;
        case 3:
            for (i = 0; i < N; i++){
                zelotes[i] = 1;
                confianca[i] = 2.;
                if(FRANDOM < 0.5){
                    polaridade[i] = 1;
                    mag++;
                } else {
                    polaridade[i] = 0;
                }
            }
        default: break;
    }

    for(i = 0; i < N; i++){
        if(bloqueado(i)){
            moveis[N - 1 + (j - i)] = i;//ADICIONA POLOS BLOQUEADOS NO FINAL DA LISTA DE MOVEIS
            quaisMoveis[i] = N - 1 + (j - i);
        } else {
            moveis[j] = i;
            quaisMoveis[i] = j;
            j++;
        }
    }
    nMoveis = j;
}

int bloqueado(int ii){
    int i, nPolo = polaridade[ii], nZelotes = zelotes[ii];
    for(i = 0; i < 4; i++){
        nPolo += polaridade[vizinhos[ii][i]];
        nZelotes += zelotes[vizinhos[ii][i]];
    }
    return (nPolo == 0 || nPolo == 5) && nZelotes == 5;
}

void verificarCruzamentoInterface(){
    int n = 0, i, i0 = L * (L - 2) / 2, sUp, sDown, s0 = polaridade0[i0];
    if(L % 2 == 0){
        for(i = 0; i < L; i++){
            sUp = polaridade0[i0 + i];
            sDown = polaridade0[i0 + i + L];
            if(sUp == s0 && sDown == s0){
                n = n + 1;
            }

        }
    }
    interfCol = n;
}


unsigned int generateFile(void){
  char name[200], context[100];
  unsigned int id = setupRandom(0);
  if(FORCE_SEED == 1) id = (unsigned int) 123456789;
  sprintf(context, "data_pvm_C%d_BC_%d", EVOLUCAO, B);
  switch(EVOLUCAO){
  	case 0:
  		sprintf(name, "%s_L%d_I%d", context, L, CONFIGURACAO_I);
  	case 1:
  		sprintf(name, "%s_L%d", context, L);
  	case 2:
  		sprintf(name, "%s_dE%.4f", context, deltaEta);
  }
  fp1 = safeSeedOpen(context, ".dat", &id, FORCE_SEED);
  
  //fprintf(fp1,"# Initial state: %d\n",CONFIGURACAO_I);
  //fprintf(fp1,"# Linear size: %d",L);
  //if (CONFIGURACAO_I==1) fprintf(fp1,"  Radius: %d\n",RAIO);
    //               else fprintf(fp1,"\n");
  //fprintf(fp1,"# Maximum simulation time: %d\n",(int)TEMPO_MAX);
  fflush(fp1);

  return id;
}


void unique_cluster(){
	int *label_z0, *label_z1, *label_s;
	int *mat_z0, *mat_z1;
	label_z0 = smalloc(N * sizeof(int)); 
	label_z1 = smalloc(N * sizeof(int));
	label_s = smalloc(N * sizeof(int));
	mat_z0 = smalloc(N * sizeof(int)); 
	mat_z1 = smalloc(N * sizeof(int));
	int sz;
	for(int i = 0; i < N; i++){
		sz = polaridade0[i] + 2 * zelotes0[i];
		mat_z0[i] = sz == 2 ? 1 : 0;
		mat_z1[i] = sz == 3 ? 1 : 0;
	}
	//create 3 matrix, 
	// mat differ zealotery and spins
	// mat_z0 unifies agents of sz different of 2
	// mat_z1 unifies agents of sz different of 3	 
	labelCluster(label_z0, mat_z0, vizinhos, N, B);
	labelCluster(label_z1, mat_z1, vizinhos, N, B);
	labelCluster(label_s, polaridade0, vizinhos, N, B);
	l0_int = 0;
	l1_int = 0;
	lar_int = 0;
	l0_int = getInterfacialLengthWith(label_z0, vizinhos, label_z0[0], label_z0[N - 1], N, B);
	l1_int = getInterfacialLengthWith(label_z1, vizinhos, label_z1[N - 1], label_z1[0], N, B);
	lar_int = getInterfacialLengthWith(label_s, vizinhos, label_s[0], label_s[N - 1], N, B);
	free(label_z0); free(label_z1); free(label_s); free(mat_z0); free(mat_z1);
	
}
/*
int getInterfacialLengthWith(int* lab, int l1, int l2){
	int li, lj, length = 0;
	for(int i = 0; i < N; i++){
		li = lab[i];
		if(li != l1) continue;
		for(int j = 0; j < 4; j++){
			if(!isValidInteraction(i, vizinhos[i][j], N, B)) continue;
			lj = lab[vizinhos[i][j]];
			if(lj != l2) continue;
			length += 1;
		}
	}
	return length;
}
*/
void clusterNumber(int *nC, int *nPer){
	int *label, *size, *lat;
	lat = smalloc(N * sizeof(int));
	label = smalloc(N * sizeof(int));
	size = smalloc(N * sizeof(int));
	for(int i = 0; i < N; i++){
		lat[i] = polaridade0[i] + 2 * zelotes0[i];
		size[i] = 0;
	}
	labelCluster(label, polaridade0, vizinhos, N, B);
	for(int i = 0; i < N; i++){
		size[label[i]] += 1;
	}
	*nC = 0;
	*nPer = 0;
	for(int i = 0; i < N; i++){
		if(size[i] > 0){
			*nC += 1;
			if(percolates2d(label[i], label)) *nPer += 1;
		}
	}
	free(label);
	free(lat);
	free(size);	
}

void hoshen_kopelman(int *his0, int *numc, int *per){
    int i,j,*label,*siz;
    int temp1,temp2,wtemp1,wtemp2,probpercv0,probpercv1;

    //criar uma lista label de 0 a N identificando clusters
    //a lista siz guarda o tamanho da cluster i-esima
    label = smalloc(N * sizeof(int));
    siz = smalloc(N * sizeof(int));
    for (i = 0; i < N; ++i){
        label[i] = i;
        siz[i] = 0;
    }

    probpercv0=0;
    probpercv1=0;

    for (i = 0; i < N; ++i){                     /* Measure the cluster sizes */
         j = i;
         while (label[j] != j)                  /* it doesn't point to itself */
               j = label[j];                    /* follow the cluster */
         ++siz[label[j]];                       /* update the cluster size */
         label[i] = label[j];                   /* update the cluster label */
    }

    temp1 = -1;                                /* Size of the biggest cluster */
    temp2 = -1;                                /* Size of the second biggest cluster */
    wtemp1 = 0;
    wtemp2 = 0;
    *numc = 0;                                  /* number of clusters */

    for (i = 0; i < N; ++i) {
        if (siz[i] > 0){
            if (siz[i] >= L){
                if (polaridade0[i] == 0) probpercv0 += percolates2d(i, label);
                if (polaridade0[i] == 1) probpercv1 += percolates2d(i, label);
            }
            if (siz[i] >= temp1) {
                temp2 = temp1;
                temp1 = siz[i];
                wtemp2 = wtemp1;
                wtemp1 = i;
            } else if (siz[i] > temp2) {
                temp2 = siz[i];
                wtemp2 = i;
            }
            ++(*numc); /* Count total number of clusters */
          }
    }

    *per = probpercv0 + probpercv1;
    zar = 0;
    for (i = 0; i < N; ++i)
        if ((i != wtemp1) && (i != wtemp2) && (zelotes[i]==1))
           {
            zar += siz[i];

           }

    free(siz); /* from here on, we use the smaller newsiz */
    free(label);
    return;
}



bool percolates2d(int qual,int *lab) {
    bool ok1 = false,ok2 = false;
    for(int i = L; i < N; i += L){
    	if(lab[i - 1] == qual) ok1 = true;
    	if(lab[i] == qual) ok2 = true;
    	if(ok1 && ok2) break;
    }
    return ok1 && ok2;
}
