#include <stdio.h>
#include <stdlib.h>
#include <string.h>
/****************LPFileHelper*****************
    Make writable file more easy to manage
*********************************************/




FILE* safeOpen(char*, char*);
FILE* safeSeedOpen(char*, char*, unsigned int*, int);
int existFile(char*);
void writeHeader(FILE*, const char*, const char*);

/*****************safeOpen()******************
    Open a file with 'name'_0.'extension'
    Saves with an int count at the end. 
*********************************************/
FILE* safeOpen(char *name, char *extension){
	FILE *f;
	char name0[50];
	int i = 0;
	do {
		sprintf(name0, "%s_%d%s",name, i, extension);
		i += 1;
	} while (existFile(name0) == 1);
	f = fopen(name0, "w");
	return f;
}

/****************existFile()*****************
    Verify if the file with name exists
    Require extension
*********************************************/
int existFile(char *name){
	FILE *f;
	int i = 0;
	f = fopen(name, "r");
	if(f != NULL) {
		i = 1;
		fclose(f);
	}
	return i;
}

/***************safeSeedOpen()****************
    Returns a file with an odd seed;
    If the file exists return the next free 
    odd seed file;
*********************************************/
FILE* safeSeedOpen(char *name, char *extension, unsigned int *seed, int forceSeed){
	FILE *f;
	char name0[150];
	if(*seed % 2 == 0) *seed += 1;
	do {
		sprintf(name0, "%s_S%d%s",name, *seed, extension);
		*seed += 2;
		
	} while (existFile(name0) == 1 && forceSeed == 0);
	f = fopen(name0, "w");
	return f;
}

static void printCentered(FILE* f, const char* text, int width) {
        int t = strlen(text);
        if (t > width) t = width;

        int left  = (width - t) / 2;
        int right = width - t - left;

        fprintf(f, "# ║ ");
        for (int i = 0; i < left; i++)  fputc(' ', f);
        fwrite(text, 1, t, f);
        for (int i = 0; i < right; i++) fputc(' ', f);
        fprintf(f, " ║\n");
}


void writeHeader(FILE* f, const char* title, const char* author) {
    if (!f || !title) return;

    int len = strlen(title);
    const char *prefix = "Data generated by: ";

    if (author) {
        int a = strlen(prefix) + strlen(author);
        if (a > len) len = a;
    }

    fprintf(f, "# ╔");
    for (int i = 0; i < len + 2; i++) fprintf(f, "═");
    fprintf(f, "╗\n");

    printCentered(f, title, len);

    if (author) {
        char line[512];
        snprintf(line, sizeof(line), "%s%s", prefix, author);
        printCentered(f, line, len);
    }

    fprintf(f, "# ╚");
    for (int i = 0; i < len + 2; i++) fprintf(f, "═");
    fprintf(f, "╝\n");
}

